# Generated by Django 4.2.8 on 2023-12-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_chat_id_tg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id_tg',
            field=models.CharField(default=534346799, max_length=30, verbose_name='для отправки ботом уведомлений'),
            preserve_default=False,
        ),
    ]
