# Generated by Django 5.0 on 2023-12-09 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pretty', models.BooleanField(verbose_name='приятная привычка')),
                ('award', models.CharField(blank=True, max_length=300, null=True, verbose_name='вознаграждение')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('location', models.CharField(max_length=300, verbose_name='место выполнения привычки')),
                ('action_to_do', models.CharField(max_length=300, verbose_name='действия выполнения привычки')),
                ('time_to_do', models.DateTimeField(verbose_name='время, когда необходимо выполнять привычку')),
                ('time_run', models.TimeField(default=0, verbose_name='время на выполнение')),
                ('period', models.CharField(choices=[('day', 'one_to_day'), ('week', 'one_to_week'), ('month', 'one_to_month')], default='day', verbose_name='периодичность')),
                ('related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habit.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'условия привычки',
                'verbose_name_plural': 'условия привычек',
            },
        ),
    ]
