# Generated by Django 5.0 on 2023-12-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('hours', 'one_to_hours'), ('day', 'one_to_day'), ('week', 'one_to_week')], default='day', verbose_name='периодичность'),
        ),
    ]
