# Generated by Django 4.2.8 on 2023-12-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_habit_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('HOURS', 'hours'), ('DAYS', 'days')], default='DAYS', verbose_name='периодичность'),
        ),
    ]
