# Generated by Django 4.2.8 on 2023-12-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_alter_habit_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('hours', 'hours'), ('days', 'days')], default='days', verbose_name='периодичность'),
        ),
    ]
