# Generated by Django 4.2.8 on 2023-12-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0006_habit_every_run_alter_habit_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_active_notif',
            field=models.BooleanField(default=True, verbose_name='включение и отключение уведомление'),
        ),
    ]
